name: "this is staging workflow"
run-name: "this is run by ${{ github.actor }} on the event ${{ github.event_name }}"


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the repository
        uses: actions/checkout@v4
      - name: connecting to aws
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@54.175.43.151'
          privatekey: ${{ secrets.EC2_staging  }}
          command: |
            export NVM_DIR=/home/ubuntu/.nvm
            source /home/ubuntu/.nvm/nvm.sh
            cd /home/ubuntu/assignment2/
            git pull origin main
            cd App/
            killall node
            npm run dev
      
      - name: notify on success
        if: success()
        run: echo "suceeded"
      
      - name: notify on fail                  
        if: success()
        run: echo "failed" 
